vrscene:
  steps:
    check_references:
      label: "Check references"
      index: 30
      commands:
        cleanup:
          label: "Cleanup scene"
          path: "silex_maya.commands.cleanup_scene.CleanupScene"
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"
          parameters:
            filters:
              - ".obj"
              - ".fbx"
              - ".abc"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values: 
              value: !command-output "check_references:get_references:file_paths"
              hide: true
            actions:
              - "conform"
            categories:
              - "action"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "file_paths"
            output: "setup:append_conform_actions"

    conform_references:
      label: "Repath references"
      index: 40
      commands:
        repath_attributes:
          label: "Repath attributes"
          path: "silex_maya.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes: 
              value: !command-output "check_references:get_references:attributes"
              hide: true
            values: 
              value: !command-output "check_references:conform_references"
              hide: true
    export:
      label: "Export"
      index: 50
      commands:
        load_plugin:
          label: "Ensure Vray Plugin is load"
          path: "silex_maya.commands.load_plugin.LoadPlugin"
          ask_user: false
          parameters:
            plugin_name: "vrayformaya"
        export_vrscene:
          label: "Export in vrscene"
          path: "silex_maya.commands.export_vrscene.ExportVrscene"
          parameters:
            directory: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
            file_name: 
              value: !command-output "setup:build_output_path:file_name"
              hide: true
    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move"
          path: "silex_client.commands.move.Move"
          parameters:
            src: 
              value: !command-output "export:export_vrscene"
              hide: true
            dst: 
              value: !command-output "setup:build_output_path:directory"
              hide: true
        remove:
          label: "Remove temp directory"
          path: "silex_client.commands.remove.Remove"
          parameters:
            file_path: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
