ma:
  steps:
    input:
      index: 10
      hide: True
      commands:
        input:
          path: "silex_client.commands.pass.Pass"

    get_conform_location:
      label: "Get maya scene conform location"
      index: 15
      commands:
        build_bundle_path:
          label: "Build path"
          path: "silex_client.commands.build_bundle_path.BuildBundlePath"
          parameters:
            file_to_bundle:
              value: !command-output "input:input:file_paths"
            frame_set:
              value: !command-output "input:input:frame_set"
            padding:
              value: !command-output "input:input:padding"
            is_reference:
              value: !command-output "input:input:is_reference"
            output_type:
              value: "ma"

    conform_references:
      label: "Conform Maya scene's references"
      index: 20
      commands:
        focus_maya_a:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        open:
          label: "Open scene to conform"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path:
              value: !command-output "input:input:file_paths"
              hide: true
            save: True
        cleanup:
          label: "Cleanup scene"
          path: "silex_maya.commands.cleanup_scene.CleanupScene"
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"
          parameters:
            skip_existing_conformed_file:
              value: false
            skip_prompt:
              value: true
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values:
              value: !command-output "conform_references:get_references:file_paths"
              hide: true
            actions:
              - "reference_bundle"
            categories:
              - "bundle"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "file_paths"
            output: "setup:append_conform_actions"

    conform_scene:
      label: "Conform Maya scene"
      index: 30
      commands:
        repath_attributes:
          label: "Repath attributes"
          path: "silex_maya.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes:
              value: !command-output "conform_references:get_references:attributes"
              hide: true
            values:
              value: !command-output "conform_references:conform_references"
              hide: true
        focus_maya_a:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        save:
          label: "Save the maya scene to the right location"
          path: "silex_maya.commands.save.Save"
          parameters:
            file_path:
              value: !command-output "get_conform_location:build_bundle_path:full_path"
              hide: true
        focus_maya_b:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        open:
          label: "Open back the original scene"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path:
              value: !command-output "conform_references:open:old_path"
              hide: true
            save: False

    output:
      index: 45
      hide: true
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "conform_scene:save:new_path"
