fbx:
  steps:
    export:
      label: "Export"
      index: 50
      commands:
        export_fbx:
          label: "Export in FBX"
          path: "silex_maya.commands.export_fbx.ExportFBX"
          parameters:
            file_dir: !command-output "setup:build_output_path:temp_directory"
            file_name: !command-output "setup:build_output_path:file_name"
    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move"
          path: "silex_client.commands.move_file.MoveFile"
          parameters:
            file_path: !command-output "export:export_abc:export_abc"
            dst_dir: !command-output "setup:build_output_path:directory"
            from_temp: true
