obj_copy:
  steps:
    export:
      label: "Export"
      index: 50
      
      commands:
        export_obj:
          label: "Export in OBJ"
          path: "silex_maya.commands.export_obj.ExportOBJ"
          parameters:
            file_dir: !command-output  "setup:build_output_path:temp" 
            file_name: !command-output "setup:build_output_path:name" 
  steps:
    copy:
      label: "Copy"
      index: 60
      commands:
        copy:
          label: "Copy"
          path: "silex_client.commands.copy_file.CopyFile"
          parameters:
            file_path: !command-output "export:export_obj"
            dst_dir: !command-output  "setup:build_output_path:directory" 

