vrscene:
  steps:
    export:
      label: "Export"
      index: 50
      commands:
        export_abc:
          label: "Export in vrscene"
          path: "silex_maya.commands.export_verscene.ExportVrscene"
          ask_user: true
          parameters:
            file_path: !command-output "setup:build_output_path"
