obj:
  steps:
    export:
      label: "Export"
      index: 50
      commands:
        export_abc:
          label: "Export in ABC"
          path: "silex_maya.commands.export_abc.ExportABC"
          ask_user: true
          parameters:
            file_path: !command-output "setup:build_output_path"
