demo_async:
  steps:
    create_cubes:
      label: "Create Cubes"
      index: 20
      commands:
        create_cubea:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubeb:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubec:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubed:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubee:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubef:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubeg:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubeh:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubei:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubej:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubek:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubel:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubem:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cuben:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubeo:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubep:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubeq:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cuber:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubes:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubet:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubeu:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubev:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubew:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubex:
          path: "silex_maya.commands.create_cube.CreateCube"
        create_cubez:
          path: "silex_maya.commands.create_cube.CreateCube"
