ma:
  steps:
    export:
      label: "Conform"
      index: 50
      commands:
        open:
          label: "Open scene to conform"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "setup:get_conform_output:file_path"
            save: True
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"

