ma:
  steps:
    export:
      label: "Conform"
      index: 50
      commands:
        open:
          label: "Open conformed scene"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "setup:get_conform_output:file_path"
        conform_ma:
          label: "Conform from maya scene"
          path: "silex_maya.commands.conform_ma.ConformMaya"
          ask_user: true

