ma:
  steps:
    input:
      index: 10
      hide: True
      commands:
        input:
          path: "silex_client.commands.pass.Pass"
    conform_references:
      label: "Conform Maya scene's references"
      index: 20
      commands:
        focus_maya:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        open:
          label: "Open scene to conform"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "input:input:file_paths"
            save: True
        cleanup:
          label: "Cleanup scene"
          path: "silex_maya.commands.cleanup_scene.CleanupScene"
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values: !command-output "conform_references:get_references:file_paths"
            actions:
              - "conform"
            categories:
              - "action"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "file_paths"
            output: "setup:append_conform_actions"
    conform_scene:
      label: "Conform Maya scene"
      index: 30
      commands:
        get_conform_cache:
          label: "Get previous conform location"
          path: "silex_client.commands.get_stored_value.GetStoredValue"
          parameters:
            key: "build_output_path_task_id"
            key_suffix: !command-output "input:input:file_paths"
          hide: true
        get_fast_conform_cache:
          label: "Check fast conform"
          path: "silex_client.commands.get_stored_value.GetStoredValue"
          parameters:
            key: "fast_conform_enabled"
            key_suffix: !command-output "input:input:file_paths"
            default: false
          hide: true
        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path_conform.BuildOutputPathConform"
          tooltip: "Build the complete output path"
          parameters:
            task: !command-output "conform:get_conform_cache:value"
            fast_conform: !command-output "conform:get_fast_conform_cache:value"
            use_current_context: false
            create_temp_dir: false
            frame_set: !command-output "input:input:frame_set"
            output_type:
              value: "ma"
              hide: true
            files: !command-output "input:input:file_paths"
            padding: !command-output "input:input:padding"
          ask_user: true
        set_conform_cache:
          label: "Cache conform location"
          path: "silex_client.commands.set_stored_value.SetStoredValue"
          parameters:
            key: "build_output_path_task_id"
            key_suffix: !command-output "input:input:file_paths"
            value: !command-output "conform:build_output_path:task"
          hide: true
        set_fast_conform_cache:
          label: "Cache conform location"
          path: "silex_client.commands.set_stored_value.SetStoredValue"
          parameters:
            key: "fast_conform_enabled"
            key_suffix: !command-output "input:input:file_paths"
            value: !command-output "conform:build_output_path:fast_conform"
          hide: true
        repath_attributes:
          label: "Repath attributes"
          path: "silex_maya.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes: !command-output "conform_references:get_references:attributes"
            values: !command-output "conform_references:conform_references"
        
        focus_maya:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        save:
          label: "Save the maya scene to the right location"
          path: "silex_maya.commands.save.Save"
          parameters:
            file_path: !command-output "conform_scene:build_output_path:full_path"
        focus_maya:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        open:
          label: "Open back the original scene"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "conform_references:open:old_path"
            save: False
    output:
      index: 40
      hide: true
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "conform_scene:save:new_path"
