ma:
  steps:
    conform:
      label: "Conform"
      index: 50
      commands:
        get_input:
          path: "silex_client.commands.pass.Pass"
        open:
          label: "Open scene to conform"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "conform:get_input"
            save: True
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            list: !command-output "conform:get_references:file_paths"
            action: "conform"
            parameter: "setup:get_conform_output:file_path"
