ma:
  steps:
    input:
      index: 10
      hide: True
      commands:
        input:
          path: "silex_client.commands.pass.Pass"

    conform_references:
      label: "Conform Maya scene's references"
      index: 20
      commands:
        open:
          label: "Open scene to conform"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "input:input:file_paths"
            save: True
        get_references:
          label: "Get referenced files"
          path: "silex_maya.commands.get_references.GetReferences"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            list: !command-output "conform_references:get_references:file_paths"
            action: "conform"
            parameter: "setup:get_conform_output:file_path"
            label_key: "file_paths"
            output: "setup:append_conform_action"

    conform_scene:
      label: "Conform Maya scene"
      index: 30
      commands:
        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          parameters:
            output_type:
              value: "ma"
              hide: true
          ask_user: true
        repath_attributes:
          label: "Repath attributes"
          path: "silex_maya.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes: !command-output "conform_references:get_references:attributes"
            values: !command-output "conform_references:conform_references"
        save:
          label: "Save the maya scene to the right location"
          path: "silex_maya.commands.save.Save"
          parameters:
            file_path: !command-output "conform_scene:build_output_path:full_path"
        open:
          label: "Open back the original scene"
          path: "silex_maya.commands.open.Open"
          parameters:
            file_path: !command-output "conform_references:open:old_path"
            save: False

    output:
      index: 40
      hide: true
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "conform_scene:save:new_path"
