build:
  shelf: "build"
  hide: true
  thumbnail: "build.svg"

  steps:
    save:
      label: "Save"
      index: 50
      commands:
        build_work_path:
          path: "silex_client.commands.build_work_path.BuildWorkPath"
        focus_maya:
          label: "Focus DCC"
          path: "silex_client.commands.focus.Focus"
        save_scene:
          path: "silex_maya.commands.save.Save"
          parameters:
            file_paths: !command-output "save:build_work_path"
