increment_and_save.yaml:
  hide: true
  steps:
    increment_and_save.yaml:
      label: "Save"
      index: 50
      commands:
        build_work_path:
          path: "silex_client.commands.build_work_path.BuildWorkPath"
          parameters:
            use_increment:
              value: true
        save_scene:
          path: "silex_maya.commands.save.Save"
          parameters:
            file_path: !command-output "save:build_work_path"
